app:
  name: yousaf-baloch-md
  
services:
  - name: whatsapp-bot
    type: web
    
    build:
      type: buildpack
      builder: heroku/nodejs
    
    instance_type: free
    regions:
      - was
    
    scaling:
      min: 1
      max: 1
    
    ports:
      - port: 3000
        protocol: http
    
    env:
      - name: SESSION_ID
        value: ""
      - name: PREFIX
        value: "."
      - name: MODE
        value: "public"
    
    health_checks:
      - http:
          port: 3000
          path: /
