name: yousaf-baloch-md
services:
  - name: bot-service
    type: worker
    git:
      repository: https://github.com/musakhanbaloch03-sad/YOUSAF-BALOCH-MD
      branch: main
    build:
      buildpackName: nodejs
    run:
      command: node index.js
    env:
      - key: NODE_ENV
        value: production
    instance_type: free
    auto_deploy: true
