services:
  - type: worker
    name: yousaf-baloch-md
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install --no-audit --no-fund --legacy-peer-deps
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false
      - key: PREFIX
        value: "."
      - key: MODE
        value: public
      - key: NODE_ENV
        value: production
      - key: TIMEZONE
        value: Asia/Karachi
      - key: LANGUAGE
        value: en
      - key: APP_NAME
        value: YOUSAF-BALOCH-MD
      - key: AUTO_READ
        value: "false"
      - key: AUTO_READ_STATUS
        value: "true"
      - key: AUTO_LIKE_STATUS
        value: "true"
      - key: AUTO_REACT
        value: "false"
      - key: ANTI_LINK
        value: "false"
      - key: ANTI_BAD
        value: "false"
      - key: ANTI_SPAM
        value: "false"
      - key: ANTI_CALL
        value: "false"
      - key: ANTI_VIEW_ONCE
        value: "false"
      - key: WELCOME
        value: "false"
      - key: GOODBYE
        value: "false"
      - key: MAX_WARN
        value: "3"
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENWEATHER_KEY
        sync: false
      - key: CRICKET_API_KEY
        sync: false
      - key: OMDB_API_KEY
        sync: false
      - key: EXCHANGE_API_KEY
        sync: false
      - key: PIXABAY_KEY
        value: "44996331-cd5ee38a4e4da3d32df5d0e7e"
      - key: DEFAULT_CITY
        value: Lahore
      - key: DEFAULT_COUNTRY
        value: Pakistan
      - key: RAMADAN_AUTO_MSG
        value: "true"
      - key: START_BALANCE
        value: "500"
      - key: DAILY_REWARD
        value: "200"
      - key: ECONOMY_CURRENCY
        value: Coins
      - key: MONGODB_URI
        sync: false
